---
- name: Ensure install directory existence
  ansible.builtin.file:
    path: "{{ fabmc_install_dir }}"
    state: directory
    mode: "0755"

- name: Ensure sub directories existence
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ fabmc_install_dir }}/bin"
    - "{{ fabmc_install_dir }}/workspace"
    - "{{ fabmc_install_dir }}/workspace/mods"

- name: "Get the status of Minecraft Server Launcher {{ fabmc_minecraft_version }} Fabric Loader {{ fabmc_fabric_loader_version }} Installer {{ fabmc_installer_version }} jar file"
  ansible.builtin.stat:
    path: "{{ fabmc_install_dir }}/bin/minecraft_server_launcher.{{ fabmc_minecraft_version }}-{{ fabmc_fabric_loader_version }}-{{ fabmc_installer_version }}.jar"
  register: minecraft_server_launcher_version_jar_file

- name: Download Minecraft Server Launcher jar file
  ansible.builtin.get_url:
    url: "https://meta.fabricmc.net/v2/versions/loader/{{ fabmc_minecraft_version }}/{{ fabmc_fabric_loader_version }}/{{ fabmc_installer_version }}/server/jar"
    dest: "{{ fabmc_install_dir }}/bin/server.jar"
    mode: "0644"
  when: not minecraft_server_launcher_version_jar_file.stat.exists

- name: Get the status of Minecraft Server Launcher jar file
  ansible.builtin.stat:
    path: "{{ fabmc_install_dir }}/bin/server.jar"
    checksum_algorithm: sha1
  register: minecraft_server_launcher_jar_file
  when: not minecraft_server_launcher_version_jar_file.stat.exists

# TODO: need to build an API client for automating checksum provisioning into vars
# - name: Fail if downloaded Minecraft Server Launcher jar file checksum does not match
#   ansible.builtin.fail:
#     msg: "Downloaded Minecraft Server Launcher jar file checksum {{ minecraft_server_launcher_jar_file.stat.checksum }} does not match the expected checksum {{ minecraft_versions[fabmc_minecraft_version]['sha1'] }}"
#   when: not minecraft_server_launcher_version_jar_file.stat.exists and minecraft_server_launcher_jar_file.stat.checksum != minecraft_versions[fabmc_minecraft_version]['sha1']

- name: "Copy downloaded Minecraft Server Launcher jar file as Minecraft Server Launcher {{ fabmc_minecraft_version }} jar file"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ fabmc_install_dir }}/bin/server.jar"
    dest: "{{ fabmc_install_dir }}/bin/minecraft_server_launcher.{{ fabmc_minecraft_version }}-{{ fabmc_fabric_loader_version }}-{{ fabmc_installer_version }}.jar"
    mode: "0644"
  when: not minecraft_server_launcher_version_jar_file.stat.exists and minecraft_server_launcher_jar_file.stat.exists

- name: Delete downloadedMinecraft Server Launcher jar file
  ansible.builtin.file:
    path: "{{ fabmc_install_dir }}/bin/server.jar"
    state: absent

- name: "Get the status of Minecraft Server Launcher jar file"
  ansible.builtin.stat:
    path: "{{ fabmc_install_dir }}/bin/minecraft_server_launcher.jar"
  register: minecraft_server_launcher_jar_file

- name: "Ensure Minecraft Server Launcher jar file or symlink does not exist"
  ansible.builtin.file:
    path: "{{ fabmc_install_dir }}/bin/minecraft_server_launcher.jar"
    state: absent
  when: not minecraft_server_launcher_jar_file.stat.exists

- name: Create symbolic link for Minecraft Server Launcher jar file
  ansible.builtin.file:
    src: "{{ fabmc_install_dir }}/bin/minecraft_server_launcher.{{ fabmc_minecraft_version }}-{{ fabmc_fabric_loader_version }}-{{ fabmc_installer_version }}.jar"
    dest: "{{ fabmc_install_dir }}/bin/minecraft_server_launcher.jar"
    state: link

- name: "Get the status of Fabric API {{ fabmc_fabric_api_version }} jar file"
  ansible.builtin.stat:
    path: "{{ fabmc_install_dir }}/workspace/mods/fabric-api-{{ fabmc_fabric_api_version }}.jar"
  register: fabric_api_version_jar_file

- name: Download Fabric API jar file
  ansible.builtin.get_url:
    url: "{{ fabric_api_versions[fabmc_fabric_api_version]['url'] }}"
    dest: "{{ fabmc_install_dir }}/workspace/mods/fabric-api-{{ fabmc_fabric_api_version }}.jar"
    mode: "0644"
  when: not fabric_api_version_jar_file.stat.exists

- name: Get the status of downloaded Fabric API jar file
  ansible.builtin.stat:
    path: "{{ fabmc_install_dir }}/workspace/mods/fabric-api-{{ fabmc_fabric_api_version }}.jar"
    checksum_algorithm: sha1
  register: fabric_api_jar_file
  when: not fabric_api_version_jar_file.stat.exists

- name: Fail if downloaded Fabric API jar file checksum does not match
  ansible.builtin.fail:
    msg: "Downloaded Fabric API jar file checksum {{ fabric_api_jar_file.stat.checksum }} does not match the expected checksum {{ fabric_api_versions[fabmc_fabric_api_version]['sha1'] }}"
  when: not fabric_api_version_jar_file.stat.exists and fabric_api_jar_file.stat.checksum != fabric_api_versions[fabmc_fabric_api_version]['sha1']

- name: Register Fabric mods directory
  ansible.builtin.find:
    paths: "{{ fabmc_install_dir }}/workspace/mods/"
    recurse: false
  register: fabric_mods_dir

- name: Delete unexpected Fabric mods
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ fabric_mods_dir.files }}"
  when:
    - item.path | basename is not match('^fabric-api-')
    - item.path | basename | replace('-', '') is not search(fabmc_fabric_mods | map('replace', '-', '') | join('|'))

- name: Ensure Python dependencies for fabric_mods module
  ansible.builtin.pip:
    name:
      - conflog
      - modrinth-api-wrapper
      - requests
    state: present
  run_once: true

- name: Install Fabric mods
  fabric_mods:
    mods: "{{ fabmc_fabric_mods }}"
    minecraft_version: "{{ fabmc_minecraft_version }}"
    install_dir: "{{ fabmc_install_dir }}"

# Minecraft server would add any missing properties with default values
# hence it's not necessary to specify all properties in fabmc_server_properties.
- name: "Set Minecraft server configuration values"
  ansible.builtin.lineinfile:
    path: "{{ fabmc_install_dir }}/workspace/server.properties"
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}={{ item.value }}'
    create: yes
    mode: "0644"
  loop: "{{ fabmc_server_properties | dict2items }}"

- name: "Get the status of Minecraft Server service file"
  ansible.builtin.stat:
    path: "/etc/systemd/system/{{ fabmc_install_id }}.service"
  register: minecraft_service_file

- name: Get the status of Minecraft Server Launcher start script file
  ansible.builtin.stat:
    path: "{{ fabmc_install_dir }}/bin/start.sh"
  register: minecraft_start_script_file

- name: Create Minecraft Server Launcher start script
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      java {{ fabmc_java_opts }} -jar {{ fabmc_install_dir }}/bin/minecraft_server_launcher.jar nogui
    dest: "{{ fabmc_install_dir }}/bin/start.sh"
    mode: "0755"
  when: not minecraft_start_script_file.stat.exists

- name: "Create Minecraft Server service file"
  become: yes
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Minecraft Java
      After=network.target

      [Service]
      ExecStart={{ fabmc_install_dir }}/bin/start.sh
      Environment=PATH={{ fabmc_env_path }}
      WorkingDirectory={{ fabmc_install_dir }}/workspace/
      Restart=on-failure
      RestartSec=10s
      User={{ fabmc_os_user }}

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/{{ fabmc_install_id }}.service"
    mode: "0644"
  when: not minecraft_service_file.stat.exists

- name: "Check init system"
  ansible.builtin.command: ps -p 1 -o comm=
  changed_when: false
  register: init_system_check

- name: "Enable Mincraft Server service with systemd"
  become: yes
  ansible.builtin.systemd:
    name: "{{ fabmc_install_id }}.service"
    enabled: yes
    state: stopped
  when: init_system_check.stdout.strip() == "systemd"

- name: "Accept Minecraft EULA"
  ansible.builtin.lineinfile:
    path: "{{ fabmc_install_dir }}/workspace/eula.txt"
    regexp: '^eula=true'
    line: 'eula=true'
    create: yes
    mode: "0644"
  when: fabmc_eula_accepted

- name: "Create aliases for Minecraft Server generic utilities"
  ansible.builtin.include_role:
    name: ansible-roles.bash_aliases
  vars:
    bash_aliases:
      - alias: "{{ fabmc_install_id }}-conf"
        command: "vi {{ fabmc_install_dir }}/workspace/server.properties"
      - alias: "{{ fabmc_install_id }}-log"
        command: "tail -f {{ fabmc_install_dir }}/workspace/logs/latest.log"

- name: "Create aliases for Minecraft Server systemd utilities"
  ansible.builtin.include_role:
    name: ansible-roles.bash_aliases
  vars:
    bash_aliases:
      - alias: "{{ fabmc_install_id }}-start"
        command: "systemctl start {{ fabmc_install_id }}.service"
      - alias: "{{ fabmc_install_id }}-stop"
        command: "systemctl stop {{ fabmc_install_id }}.service"
      - alias: "{{ fabmc_install_id }}-status"
        command: "systemctl status {{ fabmc_install_id }}.service"
      - alias: "{{ fabmc_install_id }}-start-log"
        command: "journalctl -u {{ fabmc_install_id }}"
  when: init_system_check.stdout.strip() == "systemd"
